// <auto-generated />
using IreneAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IreneAPI.Migrations
{
    [DbContext(typeof(IreneAPIContext))]
    [Migration("20240927175133_Updating with authentication")]
    partial class Updatingwithauthentication
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IreneAPI.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000.0,
                            Email = "Dyna123@gmail.com",
                            FirstName = "Emmanuel",
                            LastName = "Mojiboye",
                            Password = "Dynasty"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 20000.0,
                            Email = "Dyna123@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "Dynasty"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 40000.0,
                            Email = "Dyna123@gmail.com",
                            FirstName = "Racheal",
                            LastName = "Jackson",
                            Password = "Dynasty"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
